services:
  - type: web
    name: telegram-watermark-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    autoDeploy: true
    # Add your Telegram Bot Token as an environment variable
    # This is more secure than hardcoding it in main.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false # Set to true if you want Render to manage this secret from your repo
        value: "7888649373:AAF_FduB3mtvBddI9QICLgNIOFooii987Ss" # Replace with your actual bot token

